### ISSUE TITLE
About camera coordinate system

### ISSUE THREAD

**Issue by jeb0813** [tobias-kirschstein/nersemble#12]
Hi @tobias-kirschstein , I'm confused with the cam extrinsic and intrinsic. 
The paper wrote:
>We estimate an individual extrinsic and a shared intrinsic camera
matrix by employing a fine checkerboard in combination with a
bundle adjustment optimization procedure.

I use colmap to estimate extrinsic and intrinsic to reproduce reconstruct on other dataset, but I canot get correct params.
So I did an experiment on nersemble using colmap, and I got roughly same numerical value but positive and negative differs a lot.
I visualized the estimate results and it looks same with the cam array in the paper, so I suggest that might be a coordinate system problem.

Colmap outputs should be opencv, what's the coordinate system in NeRSemble?

Thank you.

**Comment by jeb0813** [comment]
I checked [issue_9](https://github.com/tobias-kirschstein/nersemble/issues/9#issue-2232613124), but that doesn't explains why colmap output not matching the metadata in nerfsemble. :sob:

**Comment by tobias-kirschstein** [comment]
Hi,
Can you share a visualization of your colmap poses? 
You can use the [dreifus](https://github.com/tobias-kirschstein/dreifus) library for quickly visualizing camera poses. It is expected that you won't get the same world space since you are not using a calibration checkerboard with metrical distances. But that shouldn't matter for the method as long as the scale of the world space is roughly metrical.

**Comment by KaneLindsay** [comment]
I loaded custom data successfully with my own multi-view camera setup with the coordinate system plotted here:

![coordinates](https://github.com/tobias-kirschstein/nersemble/assets/65425526/949eef23-2daa-44b8-b466-6b9605558467)

X increases to the right
Y increases downwards
Z increases forward

**Comment by jeb0813** [comment]
Hi @tobias-kirschstein and @KaneLindsay , this is colmap output in colmap.
![colmap_visual](https://github.com/tobias-kirschstein/nersemble/assets/57085763/5e31b600-d6f5-403e-b63a-ca14b75fc481)

This is colmap visual in [dreifus](https://github.com/tobias-kirschstein/dreifus). Really small and sparse cameras.
![colmap_visual_dreifus](https://github.com/tobias-kirschstein/nersemble/assets/57085763/2dc8f409-26a1-459b-bdb4-3c0b2e370f25)


This is meta NeRSemble in [dreifus](https://github.com/tobias-kirschstein/dreifus).
![meta_visual_dreifus](https://github.com/tobias-kirschstein/nersemble/assets/57085763/61e82211-e4ee-4740-94be-cbec3423ea33)

Colmap visualization in colmap looks same with meta NeRSemble in dreifus. But Colmap visualization in dreifus seems weird.

The colmap ouput is OpenCV, so there must be some convertion L missed.
What's the possible reason account for this？

Thank you for the reply!

**Comment by tobias-kirschstein** [comment]
Hi  @jeb0813 ,
thanks for the visualizations. To me, that just looks like COLMAP gives you a different world-space scale. Note the positions of the cameras from NeRSemble are all within 1 unit distance of the origin, while the output of COLMAP seems to be giving you camera positions with 5 or more units distance to the origin.
This is somewhat expected since COLMAP cannot know what 1 unit should mean in your scene. 
You could just multiply the translation part of the cam2world matrices that you get from COLMAP with a small factor (say 0.2, effectively shrinking the world space by 5x) and that should bring the cameras closer to the origin where the NeRSemble cameras are. 
In terms of 3D reconstructions it does not really matter what scale the world space has. The only point where it becomes relevant is if you have a 3D bounding box where everything outside is assumed to be empty. In the case of NeRSemble, there is a tight 3D bounding box around the reconstructed head to avoid having too many floaters. Therefore, if your world-space has a vastly different scale (as it seems to be the case for your COLMAP poses), the 3D reconstruction will fail since most of the reconstruction would be outside the bounding box. Instead of ensuring your world space has roughly metric scale, you can of course also adjust the size of the bounding box in the train script.

**Comment by MuQoe** [comment]
I have segmented videos from the NeRSemble dataset into frames, and the data is structured as data/images/{Frame_idx}/image_{Camera_idx}.png. I am trying to use COLMAP to derive camera parameters by setting the entire dataset as the image path (image_path=/data). However, I am stuck at the exhaustive matcher step, as I have not been able to run it successfully to obtain any results. Could anyone guide me on how to properly use COLMAP for this dataset structure to effectively retrieve camera parameters?

**Comment by tobias-kirschstein** [comment]
Hi, you should not need to run COLMAP yourself to obtain camera calibration for NeRSemble. They are already provided as part of the dataset. The README explains the format of the extrinsics and how to load them

**Comment by tobias-kirschstein** [comment]
Hi, you should not need to run COLMAP yourself to obtain camera calibration for NeRSemble. They are already provided as part of the dataset. The README explains the format of the extrinsics and how to load them.
