### ISSUE TITLE
Extract .ply or .obj file

### ISSUE THREAD

**Issue by sanbuddhacharyas** [tobias-kirschstein/nersemble#2]
Can we extract .ply or .obj (any 3d model)?

**Comment by tobias-kirschstein** [comment]
Hi San,

Thank you for your interest in the NeRSemble project.
Since the code is based on nerfstudio, it should in principle be possible to extract 3D geometry per timestep using their [geometry exporting pipeline](https://docs.nerf.studio/en/latest/quickstart/export_geometry.html).
However, we have not used it for this project, and it would probably require some code-changes to handle the dynamic case, starting with their script: https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/scripts/exporter.py

Please let me know, if you manage to export something. Would be interesting to see.

Best,
Tobias
