### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by lxzyuan** [tobias-kirschstein/nersemble#4]
Hello,

I'm interested in running your code to reproduce the results presented in your paper. Could you please specify the hardware requirements? Specifically, I'm interested in the following:

- RAM requirements
- GPU memory (VRAM) requirements
- Any other hardware dependencies

Would it be possible to achieve the paper's results using an NVIDIA RTX 3090 or 4090?

Thanks!

**Comment by tobias-kirschstein** [comment]
Hi, 

thanks for your interest in NeRSemble.
The GPU requirements are listed in the README:
- RTX A6000 GPU (48GB)
The biggest screw to get VRAM consumption down is probably the `--n_hash_encodings` flag because it controls the number of hash grids that are used. The default is `32` which we used for our results, but as we show in the paper, using `16` only slightly worsens the result, but it might almost half the required VRAM. 

Regarding RAM requirements, it can go up to 200G but this is just due to caching in the dataloader (for speed reasons). If you don't have RAM lying around, you can easily reduce the caching. Per default, it caches 10k train samples, but you can turn that number down as much as you want. I added the `--max_cached_images` option to the train script for that. Thanks for the hint. 

To exactly reproduce the paper results with the same architecture on a 24G GPU, your only chance currently would be to set the `--max_n_samples_per_batch` to a low value which will reduce the memory consumption of forward/backward passes, but make it quite slow. However, in the README you can also find official metrics as well as trained models which might be enough for your use-case?

Best,
Tobias
